### ISSUE TITLE
Sample

### ISSUE THREAD

**Issue by renancaraujo** [globocom/react-native-draftjs-render#10]
There is a problem with the sample.
After cloned, installed and run-android, the packager keeps popping error 500:
"...react-native-draftjs-render/src/getblocks doesn't exist"

**Comment by Canedo** [comment]
Hey.

Have you installed the project with `npm install` or `make setup`?

**Comment by renancaraujo** [comment]
Hey,
I used `npm install`
npm version: `4.0.5`

**Comment by Canedo** [comment]
To improve our development workflow, we've created a script `sync-lib` that copies lib files to sample.
This is useful because we can edit our lib and see the results automatically (live reload), otherwise we would keep reinstalling the lib everytime...

`npm install` doesn't run `sync-lib` but `make setup` does, that's why we advise to use it :)

**Comment by renancaraujo** [comment]
Didn't know about that, everything is right now.
Thank you very much for your help.
