### ISSUE TITLE
Does this project allow editing of content?

### ISSUE THREAD

**Issue by allforabit** [globocom/react-native-draftjs-render#41]
Sorry this may seem like a silly question, but does this project support editing of content? I have downloaded the project and ran the sample but it seems to be read only. Thanks for the project!

**Comment by raphaelpor** [comment]
Heelo @allforabit!
No, this project just renders the draft.js data on React Native.

Thanks for your question!

**Comment by donfour** [comment]
Sorry for reopening this issue.

Would it be possible to build a native rich text editor on top of this project, using Draftjs's [EditorState](EditorState) and [ContentState](https://draftjs.org/docs/api-reference-content-state)? Since all available React Native rich text editor libraries are pretty crappy and I'm thinking of implementing it myself.

edit: I dove into Draft's source code and holy crap it seems like a lot of work

**Comment by raphaelpor** [comment]
It's possible. But I think rich text editors only works inside WebViews. =/

**Comment by donfour** [comment]
@raphaelpor How come? A rich text editor just boils down something that can render and edit the `EditorState` right?
